name: pasar_petani
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  build_runner: ^2.4.7
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3
  flutter_svg: ^2.0.7
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  lecle_bubble_timeline: ^0.0.1+1
  lottie: ^2.7.0
  metrics: ^0.2.2
  mockito: ^5.4.4
  timeline_tile: ^2.0.0
  timelines: ^0.1.0

dev_dependencies:
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"
  min_sdk_android: 21
